### PR TITLE
Change source of data in check-ram - closes #14

### LINKED ISSUE #14: Use /proc instead of free -m
Hi,

there is one serious problem with check-ram.rb:

``` ruby
`free -m`.split("\n").drop(1).each do |line|
free_ram = line.split[3].to_i if line =~ /^-\/\+ buffers\/cache:/ # rubocop:disable RegexpLiteral
```

It is not best way to relate on free -m. Why? Output can be different on different distributions. f.e.
Centos 6:

``` bash
[root@centos6]# free -m
             total       used       free     shared    buffers     cached
Mem:          8192       1191       7000          2          0        953
-/+ buffers/cache:        237       7954
Swap:         4096          0       4096
```

Centos 7:

``` bash
[root@centos7]# free -m
              total        used        free      shared  buff/cache   available
Mem:           8192         429         956           3        6806        7633
Swap:          4096         198        3897
```

This is causing false-positives in monitoring, because calling script gives output:

``` bash
[root@centos7]# /opt/sensu/embedded/bin/check-ram.rb
CheckRAM CRITICAL: 0% free RAM left
```

I think it will be better to use /proc/meminfo - there is very small chance to change of file format.

### PR DESCRIPTION
**Pull request by 11mariom**
Hi,

I edited check to fix issue I reported (#14). It works on Linux very well. I tried using lib for vmstat - but I cannot get with it values of buffers/cache ;(

### CODE REVIEW

**Comment by mattyjones** [comment]
@11mariom I will take a look at this but I will say I am not inclined to use proc unless absolutely necessary.

@tas50  you agree ?

**Comment by 11mariom** [comment]
@mattyjones well - I had to do something to fix failing nodes. I know it is not best way to do it, but... it is better than using `free -m | grep buffers` - as it will not fail on CentOS 7

**Comment by mattyjones** [comment]
@11mariom Can you rebase this and I will merge

Thanks

**Comment by 11mariom** [comment]
@mattyjones what do you want me to rebase?

**Comment by analytically** [comment]
I think he meant rebase the PR.

**Comment by eheydrick** [comment]
Bump for rebase.

**Comment by majormoses** [comment]
I think this can be closed as the vmstat rewrite has landed.

**Comment by eheydrick** [comment]
Closing as check-ram uses vmstat now.

**Pull request closed without merging**
