### PR TITLE
BugFix: Fixed errors with free calls on some Distros

### PR DESCRIPTION
**Pull request by rs-mrichmond**
Used code from check-memory-percent.sh to fix check-memory.sh
Fixed free calls on some systems (Ubuntu 16.04) 

Fixes Issue #28

### CODE REVIEW

**Comment by eheydrick** [comment]
I'm getting `MEM UNKNOWN -` on Ubuntu 16.04. Looks like the first command is succeeding even though it's not outputting anything. I think it just needs `set -o pipefail` above the first command. Can you take a look.

**Comment by rs-mrichmond** [comment]
Looks like it works

**Comment by rs-mrichmond** [comment]
All fixed.

**Comment by eheydrick** [comment]
Thanks @rs-mrichmond!

**Pull request merged**
