### PR TITLE
closes #46

### LINKED ISSUE #46: Hardcoded threshold values in check-ram.rb override command line values
Following line override warning and critical threshold set when using "-u" or "--used" memory values.

[L88](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/bin/check-ram.rb#L88)      config[:warn] = 90
[L89](https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/bin/check-ram.rb#L89)      config[:crit] = 95

If the current memory usage is at 91% and threshold as set as follows, it will not alert as threshold set on command line are overridden by above two lines

/opt/sensu/embedded/bin/ruby check-ram.rb --used -w 80 -c 90

Expected behaviour:

CheckRAM CRITICAL: 91% RAM used

Actual 

CheckRAM WARNING: 91% RAM used

### PR DESCRIPTION
**Pull request by majormoses**
## Fixes
#46
#### General
- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)
- [x] Update README with any necessary configuration snippets
- [x] Binstubs are created if needed
- [x] RuboCop passes
- [x] Existing tests pass 
#### Known Compatablity Issues

remove hardcoded values when using `--used`

### CODE REVIEW

**Comment by sstarcher** [comment]
To keep with the original functionality would it make sense for when --used is supplied to do

config[:warn] = 100 - config[:warn]

**Comment by majormoses** [comment]
@sstarcher the problem is that if `--used` is specified we are now overwriting what they may have specified...I think its just better to say if you are using `--used` which is not default you should specify your own values...

**Comment by sstarcher** [comment]
I think the best design would to remove the `--used` option entirely.

**Comment by majormoses** [comment]
@sstarcher not sure I agree, what is your rationale? If we were to go with best case design I would argue to remove behavior of `--free` rather than `--used`; most checks I have seen are more geared to crossing a threshold as opposed to under a threshold (not that they don't exist). Maybe its just me but when thinking about some number  of a particular resource I tend to think in terms of in use rather than how much is free (yes its a subtle difference).

If we are to fix the reported bug without removing functionality I think the  proposed solution makes sense. If we are ok with removing functionality I think it makes more sense to to the reverse of what you proposed and do a major rev to avoid it breaking people using existing functionality.

**Comment by sstarcher** [comment]
I don't agree that your changes does not break existing users.  If anyone is currently using the plugin and is using --used after your change they will always see alerts as they will have thresholds of 5 and 10.  My recommendation above for 

`config[:warn] = 100 - config[:warn]`

**Comment by majormoses** [comment]
@sstarcher sorry I have been MIA (traveling for work), after reading your thoughts I agree that pretty much any good change is a breaking change at this point because the original feature was flawed. the reason I dont like `config[:warn] = 100 - config[:warn]` is because it forces you to think of things in terms of free even when using `--used` which is I think more confusing. I think the best case scenario at this point is to accept this removal of overwriting of cli options and make this a major rev change. While this has the potential of setting off a few alerts for people it would be a major version bump so it should not happen to anyone locking the version and I would rather if we are to have a breaking change I would rather it alert falsely then pass silently. This restores the plugin to sane defaults and if you want to do something other than defaults then everything works as intended. if there was a way to check if the value is default or not then we could modify this to be less breaking but I am unfamiliar with a way of doing something like assuming we know the value of the default and hope that if someone changes the default at some point they update both places.

**Comment by sstarcher** [comment]
@majormoses That sounds reasonable.  Update the revision to a major update and I'll merge.

**Comment by majormoses** [comment]
@sstarcher ready for a review and release, thanks

**Comment by majormoses** [comment]
@sstarcher can we please get a release as this is a major change?

**Pull request merged**
